version: '3.5'

services:
  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "443:443"
    networks:
      - local
    depends_on:
      - getService
      - postService
  getService:
    image: get_service
    build: ./get_service
    networks:
      - local
    restart: unless-stopped
    depends_on:
      - database
  postService:
    image: post_service
    build: ./post_service
    networks:
      - local
    restart: unless-stopped
    depends_on:
      - database
  database:
    image: mongo
    volumes:
      - database:/data/db
    networks:
      - local
    restart: unless-stopped
networks:
  local:
volumes:
  database:

